service:
  lang: en_US
  host: "0.0.0.0"
  public_port: "30975"
  private_port: "30976"
mysql:
  username: "root"
  password: "123456"
  db_host: "127.0.0.1"
  db_port: "3306"
  db_name: "sap_cert_mgt"
  charset: "utf8"
  timeout: "10s"
  timeout_read: "30s"
  timeout_write: "30s"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 500
etcd:
  endpoints:
    - 127.0.0.1:2379
  timeout: 5
  path_crt: ""
  path_key: ""
  path_ca: ""
log:
  log_dir: "/var/log/sap-cert-mgt"
  log_name: "sap-cert-mgt.log"
