// Code generated by MockGen. DO NOT EDIT.
// Source: ./cert.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	model "sap_cert_mgt/infra/model"

	gomock "github.com/golang/mock/gomock"
)

// MockCertRepoInterface is a mock of CertRepoInterface interface.
type MockCertRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCertRepoInterfaceMockRecorder
}

// MockCertRepoInterfaceMockRecorder is the mock recorder for MockCertRepoInterface.
type MockCertRepoInterfaceMockRecorder struct {
	mock *MockCertRepoInterface
}

// NewMockCertRepoInterface creates a new mock instance.
func NewMockCertRepoInterface(ctrl *gomock.Controller) *MockCertRepoInterface {
	mock := &MockCertRepoInterface{ctrl: ctrl}
	mock.recorder = &MockCertRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertRepoInterface) EXPECT() *MockCertRepoInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCertRepoInterface) Create(data *model.Cert, createdBy string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data, createdBy)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCertRepoInterfaceMockRecorder) Create(data, createdBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCertRepoInterface)(nil).Create), data, createdBy)
}

// Delete mocks base method.
func (m *MockCertRepoInterface) Delete(id int, deletedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, deletedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCertRepoInterfaceMockRecorder) Delete(id, deletedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCertRepoInterface)(nil).Delete), id, deletedBy)
}

// Enable mocks base method.
func (m *MockCertRepoInterface) Enable(id int, updatedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", id, updatedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enable indicates an expected call of Enable.
func (mr *MockCertRepoInterfaceMockRecorder) Enable(id, updatedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockCertRepoInterface)(nil).Enable), id, updatedBy)
}

// GetInfo mocks base method.
func (m *MockCertRepoInterface) GetInfo(id int) (*model.Cert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", id)
	ret0, _ := ret[0].(*model.Cert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockCertRepoInterfaceMockRecorder) GetInfo(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockCertRepoInterface)(nil).GetInfo), id)
}

// GetList mocks base method.
func (m *MockCertRepoInterface) GetList(filter map[string]interface{}, args ...interface{}) (int64, []*model.Cert, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetList", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]*model.Cert)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockCertRepoInterfaceMockRecorder) GetList(filter interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockCertRepoInterface)(nil).GetList), varargs...)
}

// Update mocks base method.
func (m *MockCertRepoInterface) Update(id int, data map[string]interface{}, updatedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data, updatedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCertRepoInterfaceMockRecorder) Update(id, data, updatedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCertRepoInterface)(nil).Update), id, data, updatedBy)
}
