// Code generated by MockGen. DO NOT EDIT.
// Source: ./notice_event.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	model "sap_cert_mgt/infra/model"

	gomock "github.com/golang/mock/gomock"
)

// MockNoticeEventRepoInterface is a mock of NoticeEventRepoInterface interface.
type MockNoticeEventRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNoticeEventRepoInterfaceMockRecorder
}

// MockNoticeEventRepoInterfaceMockRecorder is the mock recorder for MockNoticeEventRepoInterface.
type MockNoticeEventRepoInterfaceMockRecorder struct {
	mock *MockNoticeEventRepoInterface
}

// NewMockNoticeEventRepoInterface creates a new mock instance.
func NewMockNoticeEventRepoInterface(ctrl *gomock.Controller) *MockNoticeEventRepoInterface {
	mock := &MockNoticeEventRepoInterface{ctrl: ctrl}
	mock.recorder = &MockNoticeEventRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoticeEventRepoInterface) EXPECT() *MockNoticeEventRepoInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNoticeEventRepoInterface) Create(data *model.NoticeEvent) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNoticeEventRepoInterfaceMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNoticeEventRepoInterface)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockNoticeEventRepoInterface) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNoticeEventRepoInterfaceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNoticeEventRepoInterface)(nil).Delete), id)
}

// GetInfo mocks base method.
func (m *MockNoticeEventRepoInterface) GetInfo(id int) (*model.NoticeEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", id)
	ret0, _ := ret[0].(*model.NoticeEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockNoticeEventRepoInterfaceMockRecorder) GetInfo(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockNoticeEventRepoInterface)(nil).GetInfo), id)
}

// GetList mocks base method.
func (m *MockNoticeEventRepoInterface) GetList(filter map[string]interface{}, args ...interface{}) (int64, []*model.NoticeEvent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetList", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]*model.NoticeEvent)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockNoticeEventRepoInterfaceMockRecorder) GetList(filter interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockNoticeEventRepoInterface)(nil).GetList), varargs...)
}

// Update mocks base method.
func (m *MockNoticeEventRepoInterface) Update(id int, data map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNoticeEventRepoInterfaceMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNoticeEventRepoInterface)(nil).Update), id, data)
}
